### PR TITLE
Add ER diagram to the project

### PR DESCRIPTION
**Pull request by JelilFaisalAbudu**
# Requesting a review for ER diagram of the social app project

*  I have completed the data modelling for this project. therefore the diagram is ready for your review.
* The diagram can found in the docs directory as stipulated in the requirement.

## Thanks...

### CODE REVIEW

**Review by mikenath223 — CHANGES_REQUESTED** [review]
This PR has been marked as INVALID

### STATUS: ❌ INVAlID

Reason: Please ensure linting check with GitHub actions. Ensure your project is linted before requesting a re-review.

**Comment by JelilFaisalAbudu** [comment]
# Resubmitting Milestone one for review

* I have run the Rubocop linter checking on my local machine and the code passed every the test.

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team     
#### Great Job so far, everything works fine, but there are a few more things required. 
### General
- [ ] Lets activate linter checks for this project, you can use this link https://github.com/microverseinc/linters-config/tree/master/ror
- [ ] User table should have  `image_link` column ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone1/imglink.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Comment by JelilFaisalAbudu** [comment]
# GitHub Action Issue Resolved

* I've resolved the problem I was facing with the GitHub Action on my pull request. Now the action is firing.
* As for the ```image_link```, the gravatar will be used to fetch the user's image from his email address. So I don't think I need an attribute for image in the users' table

## Thanks...

**Review by wathigo — APPROVED** [review]
## Approved :heavy_check_mark: 
All requirements have been met.

**You may proceed to the next milestone.**

**Happy Hacking :computer:** 
**Simon Wathigo**

**Pull request merged**
